# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

defaults: &defaults
  working_directory: /go/src/github.com/Azure/terraform-provider-acsengine
  docker:
      # specify the version
      - image: circleci/golang:1.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
  environment:
    GOPATH: /go

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run |
            echo 'unset TF_ACC' >> $BASH_ENV
      - run:
          name: Build
          command: make build
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: Run linting rules
          command: make lint