version: 2

defaults: &defaults
  working_directory: /go/src/github.com/Azure/terraform-provider-acsengine
  docker:
      # specify the version
      - image: circleci/golang:1.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
  environment:
    GOPATH: /go

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: |
            echo `unset TF_ACC` >> $BASH_ENV
            echo `export PATH=$GOPATH/bin:$PATH` >> $BASH_ENV
      - run:
          name: Build
          command: make build
      - run:
          name: Run unit tests and shorter tests
          command: make test
      - run:
          name: Run linting rules
          command: make lint
      - run:
          name: Cluster creation acceptance tests
          command: make cluster-create
          no_output_timeout: 20m
      - run:
          name: Cluster scale acceptance tests
          command: make cluster-scale
          no_output_timeout: 20m
      - run:
          name: Cluster upgrade acceptance tests
          command: make cluster-upgrade
          no_output_timeout: 20m
      - run:
          name: Cluster acceptance tests with combined update operations
          command: make cluster-update
          no_output_timeout: 20m